# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.4.3\" \"libassimp5.4.3-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(CMAKE_COMMAND) -E cmake_progress_start /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker/CMakeFiles /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker/external/SphereMeshBlendShape//CMakeFiles/progress.marks
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(CMAKE_COMMAND) -P /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker/CMakeFiles/VerifyGlobs.cmake
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/rule:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/rule
.PHONY : external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/rule

# Convenience name for target.
SphereMeshBlendShape: external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/rule
.PHONY : SphereMeshBlendShape

# fast build rule for target.
SphereMeshBlendShape/fast:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build
.PHONY : SphereMeshBlendShape/fast

# Convenience name for target.
external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/rule:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/rule
.PHONY : external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/rule

# Convenience name for target.
SphereMeshBlendShape_autogen: external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/rule
.PHONY : SphereMeshBlendShape_autogen

# fast build rule for target.
SphereMeshBlendShape_autogen/fast:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape_autogen.dir/build
.PHONY : SphereMeshBlendShape_autogen/fast

SphereMeshBlendShape_autogen/mocs_compilation.o: SphereMeshBlendShape_autogen/mocs_compilation.cpp.o
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.o

# target to build an object file
SphereMeshBlendShape_autogen/mocs_compilation.cpp.o:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/SphereMeshBlendShape_autogen/mocs_compilation.cpp.o
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.cpp.o

SphereMeshBlendShape_autogen/mocs_compilation.i: SphereMeshBlendShape_autogen/mocs_compilation.cpp.i
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.i

# target to preprocess a source file
SphereMeshBlendShape_autogen/mocs_compilation.cpp.i:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/SphereMeshBlendShape_autogen/mocs_compilation.cpp.i
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.cpp.i

SphereMeshBlendShape_autogen/mocs_compilation.s: SphereMeshBlendShape_autogen/mocs_compilation.cpp.s
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.s

# target to generate assembly for a file
SphereMeshBlendShape_autogen/mocs_compilation.cpp.s:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/SphereMeshBlendShape_autogen/mocs_compilation.cpp.s
.PHONY : SphereMeshBlendShape_autogen/mocs_compilation.cpp.s

src/bumper_graph.o: src/bumper_graph.cpp.o
.PHONY : src/bumper_graph.o

# target to build an object file
src/bumper_graph.cpp.o:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_graph.cpp.o
.PHONY : src/bumper_graph.cpp.o

src/bumper_graph.i: src/bumper_graph.cpp.i
.PHONY : src/bumper_graph.i

# target to preprocess a source file
src/bumper_graph.cpp.i:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_graph.cpp.i
.PHONY : src/bumper_graph.cpp.i

src/bumper_graph.s: src/bumper_graph.cpp.s
.PHONY : src/bumper_graph.s

# target to generate assembly for a file
src/bumper_graph.cpp.s:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_graph.cpp.s
.PHONY : src/bumper_graph.cpp.s

src/bumper_grid.o: src/bumper_grid.cpp.o
.PHONY : src/bumper_grid.o

# target to build an object file
src/bumper_grid.cpp.o:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_grid.cpp.o
.PHONY : src/bumper_grid.cpp.o

src/bumper_grid.i: src/bumper_grid.cpp.i
.PHONY : src/bumper_grid.i

# target to preprocess a source file
src/bumper_grid.cpp.i:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_grid.cpp.i
.PHONY : src/bumper_grid.cpp.i

src/bumper_grid.s: src/bumper_grid.cpp.s
.PHONY : src/bumper_grid.s

# target to generate assembly for a file
src/bumper_grid.cpp.s:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/bumper_grid.cpp.s
.PHONY : src/bumper_grid.cpp.s

src/sphere_mesh.o: src/sphere_mesh.cpp.o
.PHONY : src/sphere_mesh.o

# target to build an object file
src/sphere_mesh.cpp.o:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/sphere_mesh.cpp.o
.PHONY : src/sphere_mesh.cpp.o

src/sphere_mesh.i: src/sphere_mesh.cpp.i
.PHONY : src/sphere_mesh.i

# target to preprocess a source file
src/sphere_mesh.cpp.i:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/sphere_mesh.cpp.i
.PHONY : src/sphere_mesh.cpp.i

src/sphere_mesh.s: src/sphere_mesh.cpp.s
.PHONY : src/sphere_mesh.s

# target to generate assembly for a file
src/sphere_mesh.cpp.s:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(MAKE) $(MAKESILENT) -f external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/build.make external/SphereMeshBlendShape/CMakeFiles/SphereMeshBlendShape.dir/src/sphere_mesh.cpp.s
.PHONY : src/sphere_mesh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SphereMeshBlendShape_autogen"
	@echo "... SphereMeshBlendShape"
	@echo "... SphereMeshBlendShape_autogen/mocs_compilation.o"
	@echo "... SphereMeshBlendShape_autogen/mocs_compilation.i"
	@echo "... SphereMeshBlendShape_autogen/mocs_compilation.s"
	@echo "... src/bumper_graph.o"
	@echo "... src/bumper_graph.i"
	@echo "... src/bumper_graph.s"
	@echo "... src/bumper_grid.o"
	@echo "... src/bumper_grid.i"
	@echo "... src/bumper_grid.s"
	@echo "... src/sphere_mesh.o"
	@echo "... src/sphere_mesh.i"
	@echo "... src/sphere_mesh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(CMAKE_COMMAND) -P /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker/CMakeFiles/VerifyGlobs.cmake
	cd /Users/davidepaollilo/Workspaces/C++/SphereMeshTweaker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

